import "dotenv/config";
import { replyQueue } from "../src/features/leads/queues/reply";

async function start() {
	replyQueue.add({
		lead_id: "7d584e16-10a2-441b-b795-33e0df0aabb3",
		content: "test reply generated by sweetreply yo!",
	});
}

start();
